INSERT INTO "especialidad" ("id", "nombre") VALUES (1, 'CLINICA MEDICA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (2, 'MEDICINA GENERAL Y DE FAMILIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (3, 'ALERGIA E INMUNOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (4, 'CARDIOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (5, 'ANGIOLOGIA GENERAL Y HEMODINAMIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (6, 'DERMATOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (7, 'ENDOCRINOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (8, 'FARMACOLOGIA CLINICA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (9, 'FISIATRIA (MEDICINA FISICA Y REHABILITACION)');
INSERT INTO "especialidad" ("id", "nombre") VALUES (10, 'GASTROENTEROLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (11, 'GENETICA MEDICA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (12, 'GERIATRIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (13, 'HEMATOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (14, 'INFECTOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (15, 'NEFROLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (16, 'NEUMONOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (17, 'NEUROLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (18, 'NUTRICION');
INSERT INTO "especialidad" ("id", "nombre") VALUES (19, 'ONCOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (20, 'REUMATOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (21, 'TERAPIA INTENSIVA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (22, 'CIRUGIA GENERAL');
INSERT INTO "especialidad" ("id", "nombre") VALUES (23, 'CIRUGIA CARDIOVASCULAR');
INSERT INTO "especialidad" ("id", "nombre") VALUES (24, 'CIRUGIA DE CABEZA Y CUELLO');
INSERT INTO "especialidad" ("id", "nombre") VALUES (25, 'CIRUGIA DE TORAX (CIRUGIA TORACICA)');
INSERT INTO "especialidad" ("id", "nombre") VALUES (26, 'CIRUGIA INFANTIL (CIRUGIA PEDIATRICA)');
INSERT INTO "especialidad" ("id", "nombre") VALUES (27, 'CIRUGIA PLASTICA Y REPARADORA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (28, 'CIRUGIA VASCULAR PERIFERICA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (29, 'COLOPROCTOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (30, 'GINECOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (31, 'NEUROCIRUGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (32, 'OBSTETRICIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (33, 'OFTALMOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (34, 'ORTOPEDIA Y TRAUMATOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (35, 'OTORRINOLARINGOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (36, 'TOCOGINECOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (37, 'UROLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (38, 'PEDIATRIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (39, 'CARDIOLOGO INFANTIL.');
INSERT INTO "especialidad" ("id", "nombre") VALUES (40, 'ENDOCRINOLOGO INFANTIL.');
INSERT INTO "especialidad" ("id", "nombre") VALUES (41, 'GASTROENTEROLOGO INFANTIL.');
INSERT INTO "especialidad" ("id", "nombre") VALUES (42, 'HEMATOLOGO INFANTIL.');
INSERT INTO "especialidad" ("id", "nombre") VALUES (43, 'INFECTOLOGO INFANTIL');
INSERT INTO "especialidad" ("id", "nombre") VALUES (44, 'NEFROLOGO INFANTIL.');
INSERT INTO "especialidad" ("id", "nombre") VALUES (45, 'NEONATOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (46, 'NEUMONOLOGO INFANTIL.');
INSERT INTO "especialidad" ("id", "nombre") VALUES (47, 'NEUROLOGO INFANTIL.');
INSERT INTO "especialidad" ("id", "nombre") VALUES (48, 'ONCOLOGO INFANTIL.');
INSERT INTO "especialidad" ("id", "nombre") VALUES (49, 'REUMATOLOGO INFANTIL.');
INSERT INTO "especialidad" ("id", "nombre") VALUES (50, 'TERAPISTA INTENSIVO INFANTIL');
INSERT INTO "especialidad" ("id", "nombre") VALUES (51, 'PSIQUIATRIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (52, 'PSIQUIATRIA INFANTO JUVENIL');
INSERT INTO "especialidad" ("id", "nombre") VALUES (53, 'ANATOMIA PATOLOGICA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (54, 'ANESTESIOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (55, 'DIAGNOSTICO POR IMAGENES');
INSERT INTO "especialidad" ("id", "nombre") VALUES (56, 'HEMOTERAPIA E INMUNOHEMATOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (57, 'MEDICINA DEL DEPORTE');
INSERT INTO "especialidad" ("id", "nombre") VALUES (58, 'MEDICINA DEL TRABAJO');
INSERT INTO "especialidad" ("id", "nombre") VALUES (59, 'MEDICINA LEGAL');
INSERT INTO "especialidad" ("id", "nombre") VALUES (60, 'MEDICINA NUCLEAR');
INSERT INTO "especialidad" ("id", "nombre") VALUES (61, 'RADIOTERAPIA O TERAPIA RADIANTE');
INSERT INTO "especialidad" ("id", "nombre") VALUES (62, 'TOXICOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (63, 'CIRUGIA Y TRUMATOLOGIA BUCOMAXILOFACIAL');
INSERT INTO "especialidad" ("id", "nombre") VALUES (64, 'PERIODONCIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (65, 'ENDODONCIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (66, 'ODONTOPEDIATRIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (67, 'ORTODONCIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (68, 'MEDICINA GENERAL');
INSERT INTO "especialidad" ("id", "nombre") VALUES (69, 'MEDICINA DE FAMILIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (70, 'MASTOLOGIA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (71, 'QUEMADOS');
INSERT INTO "especialidad" ("id", "nombre") VALUES (72, 'SALUD PUBLICA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (73, 'CIRUGIA ONCOLOGICA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (74, 'DERMATOLOGÍA PEDIÁTRICA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (75, 'EMERGENTOLOGÍA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (76, 'ELECTRO FISIOLOGÍA CARDÍACA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (77, 'ORTOPEDIA Y TRAUMATOLOGÍA INFANTIL');
INSERT INTO "especialidad" ("id", "nombre") VALUES (78, 'HEPATOLOGÍA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (79, 'HEPATOLOGÍA PEDIÁTRICA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (80, 'ALERGIA E INMUNOLOGÍA PEDIÁTRICA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (81, 'CIRUGÍA CARDIOVASCULAR PEDIÁTRICA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (82, 'ANATOMÍA PATOLÓGICA BUCALMAXILOFACIAL');
INSERT INTO "especialidad" ("id", "nombre") VALUES (83, 'DIAGNÓSTICO POR IMÁGENES BUCOMAXILOFACIAL');
INSERT INTO "especialidad" ("id", "nombre") VALUES (84, 'ODONTOLOGÍA LEGAL');
INSERT INTO "especialidad" ("id", "nombre") VALUES (85, 'CLÍNICA ESTOMATOLÓGICA');
INSERT INTO "especialidad" ("id", "nombre") VALUES (86, 'PRÓTESIS DENTOBUCOMAXILAR');
INSERT INTO "especialidad" ("id", "nombre") VALUES (87, 'ORTODONCIA Y ORTOPEDIA MAXILAR');
