INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (1, 1, 'Ciudad Autónoma de Buenos Aires', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (2, 2, 'Buenos Aires', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (3, 3, 'Catamara', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (4, 4, 'Córdoba', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (5, 5, 'Corrientes', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (6, 6, 'Entre Ríos', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (7, 7, 'Jujuy', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (8, 8, 'Mendoza', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (9, 9, 'La Rioja', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (10, 10, 'Salta', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (11, 11, 'San Juan', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (12, 12, 'San Luis', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (13, 13, 'Santa Fe', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (14, 14, 'Santiago del Estero', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (15, 15, 'Tucumán', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (16, 16, 'Chaco', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (17, 17, 'Chubut', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (18, 18, 'Formosa', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (19, 19, 'Misiones', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (20, 20, 'Neuquén', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (21, 21, 'La Pampa', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (22, 22, 'Río Negro', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (23, 23, 'Santa Cruz', 159);
INSERT INTO "provincia" ("id", "codigo", "nombre", "pais_id") VALUES (24, 24, 'Tierra del Fuego', 159);
