spring:
  application:
    name: profesional-higea
server:
  port: 36001
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

feign:
  hystrix:
    enabled: false