spring:
  application:
    name: higea-especialidades
server:
  port: 36002
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

feign:
  hystrix:
    enabled: false