INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (1, 'Mutual Integrantes del Poder Judicial', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (2, 'Centro Integral de Salud', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (3, 'Centro Phasis', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (4, 'GIRASOLES. Consultorios Integrados para la salud', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (5, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (6, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (7, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (8, 'El Arbol. Ctro. De rehabilitación neurológica y atención temprana', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (9, 'Plaza Consultorios', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (10, 'Consultorios "Del Oeste"', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (11, 'Centro de Neurociencias del Litoral', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (12, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (13, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (14, 'Aprendamos', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (15, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (16, 'Shanti espacio Interdisciplinario', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (17, 'Centro Médico Cruz Azul', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (18, 'Clínica Médica', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (19, 'Consultorios Grand Bourg', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (20, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (21, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (22, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (23, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (24, 'Servicios Sociales Centro Médico Mutual Sarmiento', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (25, 'Lazos "Espacio de Aprendizaje y atención Terapéutica"', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (26, 'Centro Privado Bonne Santé', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (27, 'Consultoiro Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (28, '"Vínculos" Ctro. Integral de Rehabilitación', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (29, 'Clínica Génesis', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (30, 'Centro Médico de Humboldt', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (31, 'Centro Clínico Kinésico', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (32, 'Institución para niños y adolescentes, sordos e hipoacúsicos', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (33, 'Alas "Centro de Vida y Salud"', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (34, 'Lazos "Espacio de Aprendizaje y atención Terapéutica"', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (35, 'Aprendamos', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (36, 'IMED', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (37, 'Consultorios Grand Bourg', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (38, 'E.P.I. "Espacio de Psicoterapias Integral"', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (39, 'Multiespacio Terapéutico', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (40, 'Huellas', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (41, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (42, 'Academia REDSA', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (43, 'Piedra Libre', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (44, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (45, 'Consultorios "Ser Uno"', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (46, 'Clínica de Niños', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (47, 'Vaiven', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (48, 'CIPEF', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (49, 'Centro para la Salud', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (50, 'Vínculos "Centro Integral de Rehabiitación"', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (51, 'Espacio Terapéutico "Ocupate"', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (52, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (53, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (54, 'Aprendamos', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (55, 'Lazos "Espacio de Aprendizaje y atención Terapéutica"', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (56, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (57, 'Clínica San Martín', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (58, 'Consultorio Médico Kinesico', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (59, 'Aprendamos', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (60, '"Lazos" Espacio de aprendizaje y atención terapéutica', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (61, 'Altea Consultorios Médicos', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (62, 'Centro Integral Galicia', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (63, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (64, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (65, 'Lazos "Espacio de Aprendizaje y atención Terapéutica"', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (66, 'Aprendamos', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (67, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (68, 'Consultorios Inter-Rieles', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (69, 'IdeA', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (70, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (71, 'Centro Integral de Salud', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (72, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (73, 'ALPI Rafaela', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (74, 'Centro Estudio VIDA', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (75, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (76, 'Los Alamos Consultorios Médicos', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (77, 'Sanatorio Premed', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (78, '"Piedra Libre" Espacio Terapéutico', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (79, 'Clínica de Especialidades', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (80, 'Clínica López y Planes', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (81, 'Consultorio Externo', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (82, 'Clinica Departamental "Las Colonias"', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (83, 'Consultorio Psicológicos y Médicos', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (84, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (85, 'Centro de Clínica Infantil', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (86, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (87, 'Clínica Blas Parera', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (88, 'A.S.I.S.', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (89, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (90, 'Clínica CIDEM', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (91, 'Recreart', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (92, 'Clínica Namasté', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (93, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (94, 'Andares', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (95, 'Centro Médico Odontológico Belgrano', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (96, 'Centro Médico French', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (97, 'S.E.R.', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (98, 'Clínica López y Planes', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (99, 'Centro Privado "Bonne Sante"', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (100, 'Consultorios Beata Clara Bosatta', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (101, 'Centro Mëdico SEM', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (102, 'Contenídos Espacio de formación y atención interdisciplinaria', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (103, 'Consultorio Particular', NULL);
INSERT INTO "centro_salud" ("id", "nombre", "especialidad_id") VALUES (104, 'Alas "Centro de Vida y Salud"', NULL);
