INSERT INTO "centro_salud" ("id", "nombre") VALUES (1, 'Mutual Integrantes del Poder Judicial');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (2, 'Centro Integral de Salud');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (3, 'Centro Phasis');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (4, 'GIRASOLES. Consultorios Integrados para la salud');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (5, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (6, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (7, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (8, 'El Arbol. Ctro. De rehabilitación neurológica y atención temprana');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (9, 'Plaza Consultorios');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (10, 'Consultorios "Del Oeste"');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (11, 'Centro de Neurociencias del Litoral');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (12, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (13, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (14, 'Aprendamos');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (15, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (16, 'Shanti espacio Interdisciplinario');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (17, 'Centro Médico Cruz Azul');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (18, 'Clínica Médica');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (19, 'Consultorios Grand Bourg');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (20, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (21, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (22, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (23, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (24, 'Servicios Sociales Centro Médico Mutual Sarmiento');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (25, 'Lazos "Espacio de Aprendizaje y atención Terapéutica"');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (26, 'Centro Privado Bonne Santé');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (27, 'Consultoiro Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (28, '"Vínculos" Ctro. Integral de Rehabilitación');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (29, 'Clínica Génesis');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (30, 'Centro Médico de Humboldt');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (31, 'Centro Clínico Kinésico');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (32, 'Institución para niños y adolescentes, sordos e hipoacúsicos');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (33, 'Alas "Centro de Vida y Salud"');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (34, 'Lazos "Espacio de Aprendizaje y atención Terapéutica"');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (35, 'Aprendamos');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (36, 'IMED');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (37, 'Consultorios Grand Bourg');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (38, 'E.P.I. "Espacio de Psicoterapias Integral"');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (39, 'Multiespacio Terapéutico');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (40, 'Huellas');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (41, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (42, 'Academia REDSA');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (43, 'Piedra Libre');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (44, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (45, 'Consultorios "Ser Uno"');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (46, 'Clínica de Niños');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (47, 'Vaiven');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (48, 'CIPEF');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (49, 'Centro para la Salud');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (50, 'Vínculos "Centro Integral de Rehabiitación"');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (51, 'Espacio Terapéutico "Ocupate"');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (52, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (53, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (54, 'Aprendamos');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (55, 'Lazos "Espacio de Aprendizaje y atención Terapéutica"');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (56, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (57, 'Clínica San Martín');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (58, 'Consultorio Médico Kinesico');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (59, 'Aprendamos');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (60, '"Lazos" Espacio de aprendizaje y atención terapéutica');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (61, 'Altea Consultorios Médicos');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (62, 'Centro Integral Galicia');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (63, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (64, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (65, 'Lazos "Espacio de Aprendizaje y atención Terapéutica"');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (66, 'Aprendamos');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (67, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (68, 'Consultorios Inter-Rieles');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (69, 'IdeA');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (70, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (71, 'Centro Integral de Salud');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (72, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (73, 'ALPI Rafaela');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (74, 'Centro Estudio VIDA');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (75, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (76, 'Los Alamos Consultorios Médicos');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (77, 'Sanatorio Premed');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (78, '"Piedra Libre" Espacio Terapéutico');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (79, 'Clínica de Especialidades');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (80, 'Clínica López y Planes');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (81, 'Consultorio Externo');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (82, 'Clinica Departamental "Las Colonias"');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (83, 'Consultorio Psicológicos y Médicos');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (84, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (85, 'Centro de Clínica Infantil');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (86, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (87, 'Clínica Blas Parera');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (88, 'A.S.I.S.');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (89, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (90, 'Clínica CIDEM');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (91, 'Recreart');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (92, 'Clínica Namasté');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (93, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (94, 'Andares');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (95, 'Centro Médico Odontológico Belgrano');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (96, 'Centro Médico French');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (97, 'S.E.R.');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (98, 'Clínica López y Planes');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (99, 'Centro Privado "Bonne Sante"');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (100, 'Consultorios Beata Clara Bosatta');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (101, 'Centro Mëdico SEM');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (102, 'Contenídos Espacio de formación y atención interdisciplinaria');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (103, 'Consultorio Particular');
INSERT INTO "centro_salud" ("id", "nombre") VALUES (104, 'Alas "Centro de Vida y Salud"');
