INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (1, 102, 'AUSTRIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (2, 103, 'BELGICA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (3, 104, 'BULGARIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (4, 106, 'CHIPRE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (5, 107, 'DINAMARCA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (6, 108, 'ESPAÑA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (7, 109, 'FINLANDIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (8, 110, 'FRANCIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (9, 111, 'GRECIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (10, 112, 'HUNGRIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (11, 113, 'IRLANDA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (12, 115, 'ITALIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (13, 117, 'LUXEMBURGO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (14, 118, 'MALTA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (15, 121, 'PAISES BAJOS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (16, 122, 'POLONIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (17, 123, 'PORTUGAL');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (18, 125, 'REINO UNIDO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (19, 126, 'ALEMANIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (20, 128, 'RUMANIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (21, 131, 'SUECIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (22, 136, 'LETONIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (23, 141, 'ESTONIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (24, 142, 'LITUANIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (25, 143, 'REPUBLICA CHECA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (26, 144, 'REPUBLICA ESLOVACA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (27, 147, 'ESLOVENIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (28, 198, 'OTROS PAISES O TERRITORIOS DE LA UNION EUROPEA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (29, 101, 'ALBANIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (30, 114, 'ISLANDIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (31, 116, 'LIECHTENSTEIN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (32, 119, 'MONACO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (33, 120, 'NORUEGA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (34, 124, 'ANDORRA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (35, 129, 'SAN MARINO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (36, 130, 'SANTA SEDE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (37, 132, 'SUIZA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (38, 135, 'UCRANIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (39, 137, 'MOLDAVIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (40, 138, 'BELARUS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (41, 139, 'GEORGIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (42, 145, 'BOSNIA Y HERZEGOVINA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (43, 146, 'CROACIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (44, 148, 'ARMENIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (45, 154, 'RUSIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (46, 156, 'MACEDONIA ');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (47, 157, 'SERBIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (48, 158, 'MONTENEGRO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (49, 170, 'GUERNESEY');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (50, 171, 'SVALBARD Y JAN MAYEN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (51, 172, 'ISLAS FEROE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (52, 173, 'ISLA DE MAN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (53, 174, 'GIBRALTAR');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (54, 175, 'ISLAS DEL CANAL');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (55, 176, 'JERSEY');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (56, 177, 'ISLAS ALAND');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (57, 436, 'TURQUIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (58, 199, 'OTROS PAISES O TERRITORIOS DEL RESTO DE EUROPA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (59, 201, 'BURKINA FASO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (60, 202, 'ANGOLA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (61, 203, 'ARGELIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (62, 204, 'BENIN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (63, 205, 'BOTSWANA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (64, 206, 'BURUNDI');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (65, 207, 'CABO VERDE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (66, 208, 'CAMERUN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (67, 209, 'COMORES');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (68, 210, 'CONGO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (69, 211, 'COSTA DE MARFIL');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (70, 212, 'DJIBOUTI');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (71, 213, 'EGIPTO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (72, 214, 'ETIOPIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (73, 215, 'GABON');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (74, 216, 'GAMBIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (75, 217, 'GHANA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (76, 218, 'GUINEA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (77, 219, 'GUINEA-BISSAU');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (78, 220, 'GUINEA ECUATORIAL');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (79, 221, 'KENIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (80, 222, 'LESOTHO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (81, 223, 'LIBERIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (82, 224, 'LIBIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (83, 225, 'MADAGASCAR');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (84, 226, 'MALAWI');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (85, 227, 'MALI');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (86, 228, 'MARRUECOS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (87, 229, 'MAURICIO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (88, 230, 'MAURITANIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (89, 231, 'MOZAMBIQUE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (90, 232, 'NAMIBIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (91, 233, 'NIGER');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (92, 234, 'NIGERIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (93, 235, 'REPUBLICA CENTROAFRICANA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (94, 236, 'SUDAFRICA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (95, 237, 'RUANDA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (96, 238, 'SANTO TOME Y PRINCIPE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (97, 239, 'SENEGAL');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (98, 240, 'SEYCHELLES');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (99, 241, 'SIERRA LEONA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (100, 242, 'SOMALIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (101, 243, 'SUDAN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (102, 244, 'SWAZILANDIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (103, 245, 'TANZANIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (104, 246, 'CHAD');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (105, 247, 'TOGO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (106, 248, 'TUNEZ');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (107, 249, 'UGANDA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (108, 250, 'REP.DEMOCRATICA DEL CONGO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (109, 251, 'ZAMBIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (110, 252, 'ZIMBABWE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (111, 253, 'ERITREA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (112, 260, 'SANTA HELENA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (113, 261, 'REUNION');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (114, 262, 'MAYOTTE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (115, 263, 'SAHARA OCCIDENTAL');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (116, 299, 'OTROS PAISES O TERRITORIOS DE AFRICA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (117, 301, 'CANADA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (118, 302, 'ESTADOS UNIDOS DE AMERICA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (119, 303, 'MEXICO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (120, 370, 'SAN PEDRO Y MIQUELON ');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (121, 371, 'GROENLANDIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (122, 396, 'OTROS PAISES  O TERRITORIOS DE AMERICA DEL NORTE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (123, NULL, '');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (124, 310, 'ANTIGUA Y BARBUDA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (125, 311, 'BAHAMAS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (126, 312, 'BARBADOS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (127, 313, 'BELICE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (128, 314, 'COSTA RICA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (129, 315, 'CUBA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (130, 316, 'DOMINICA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (131, 317, 'EL SALVADOR');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (132, 318, 'GRANADA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (133, 319, 'GUATEMALA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (134, 320, 'HAITI');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (135, 321, 'HONDURAS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (136, 322, 'JAMAICA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (137, 323, 'NICARAGUA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (138, 324, 'PANAMA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (139, 325, 'SAN VICENTE Y LAS GRANADINAS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (140, 326, 'REPUBLICA DOMINICANA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (141, 327, 'TRINIDAD Y TOBAGO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (142, 328, 'SANTA LUCIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (143, 329, 'SAN CRISTOBAL Y NIEVES');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (144, 380, 'ISLAS CAIMÁN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (145, 381, 'ISLAS TURCAS Y CAICOS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (146, 382, 'ISLAS VÍRGENES DE LOS ESTADOS UNIDOS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (147, 383, 'GUADALUPE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (148, 384, 'ANTILLAS HOLANDESAS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (149, 385, 'SAN MARTIN (PARTE FRANCESA)');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (150, 386, 'ARUBA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (151, 387, 'MONTSERRAT');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (152, 388, 'ANGUILLA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (153, 389, 'SAN BARTOLOME');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (154, 390, 'MARTINICA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (155, 391, 'PUERTO RICO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (156, 392, 'BERMUDAS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (157, 393, 'ISLAS VIRGENES BRITANICAS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (158, 398, 'OTROS PAISES O TERRITORIOS DEL CARIBE Y AMERICA CENTRAL');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (159, 340, 'ARGENTINA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (160, 341, 'BOLIVIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (161, 342, 'BRASIL');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (162, 343, 'COLOMBIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (163, 344, 'CHILE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (164, 345, 'ECUADOR');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (165, 346, 'GUYANA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (166, 347, 'PARAGUAY');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (167, 348, 'PERU');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (168, 349, 'SURINAM');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (169, 350, 'URUGUAY');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (170, 351, 'VENEZUELA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (171, 394, 'GUAYANA FRANCESA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (172, 395, 'ISLAS MALVINAS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (173, 399, 'OTROS PAISES O TERRITORIOS  DE SUDAMERICA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (174, 401, 'AFGANISTAN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (175, 402, 'ARABIA SAUDI');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (176, 403, 'BAHREIN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (177, 404, 'BANGLADESH');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (178, 405, 'MYANMAR');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (179, 407, 'CHINA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (180, 408, 'EMIRATOS ARABES UNIDOS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (181, 409, 'FILIPINAS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (182, 410, 'INDIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (183, 411, 'INDONESIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (184, 412, 'IRAQ');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (185, 413, 'IRAN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (186, 414, 'ISRAEL');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (187, 415, 'JAPON');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (188, 416, 'JORDANIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (189, 417, 'CAMBOYA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (190, 418, 'KUWAIT');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (191, 419, 'LAOS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (192, 420, 'LIBANO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (193, 421, 'MALASIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (194, 422, 'MALDIVAS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (195, 423, 'MONGOLIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (196, 424, 'NEPAL');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (197, 425, 'OMAN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (198, 426, 'PAKISTAN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (199, 427, 'QATAR');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (200, 430, 'COREA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (201, 431, 'COREA DEL NORTE ');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (202, 432, 'SINGAPUR');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (203, 433, 'SIRIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (204, 434, 'SRI LANKA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (205, 435, 'TAILANDIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (206, 437, 'VIETNAM');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (207, 439, 'BRUNEI');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (208, 440, 'ISLAS MARSHALL');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (209, 441, 'YEMEN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (210, 442, 'AZERBAIYAN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (211, 443, 'KAZAJSTAN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (212, 444, 'KIRGUISTAN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (213, 445, 'TADYIKISTAN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (214, 446, 'TURKMENISTAN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (215, 447, 'UZBEKISTAN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (216, 448, 'ISLAS MARIANAS DEL NORTE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (217, 449, 'PALESTINA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (218, 450, 'HONG KONG');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (219, 453, 'BHUTÁN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (220, 454, 'GUAM');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (221, 455, 'MACAO');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (222, 499, 'OTROS PAISES O TERRITORIOS DE ASIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (223, 501, 'AUSTRALIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (224, 502, 'FIJI');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (225, 504, 'NUEVA ZELANDA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (226, 505, 'PAPUA NUEVA GUINEA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (227, 506, 'ISLAS SALOMON');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (228, 507, 'SAMOA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (229, 508, 'TONGA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (230, 509, 'VANUATU');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (231, 511, 'MICRONESIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (232, 512, 'TUVALU');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (233, 513, 'ISLAS COOK');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (234, 515, 'NAURU');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (235, 516, 'PALAOS');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (236, 517, 'TIMOR ORIENTAL');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (237, 520, 'POLINESIA FRANCESA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (238, 521, 'ISLA NORFOLK');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (239, 522, 'KIRIBATI');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (240, 523, 'NIUE');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (241, 524, 'ISLAS PITCAIRN');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (242, 525, 'TOKELAU');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (243, 526, 'NUEVA CALEDONIA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (244, 527, 'WALLIS Y FORTUNA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (245, 528, 'SAMOA AMERICANA');
INSERT INTO "pais" ("id", "codigo", "nombre") VALUES (246, 599, 'OTROS PAISES O TERRITORIOS DE OCEANIA');
