INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (1, 'ABRAHAM', ' JUAN CARLOS (h)');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (2, 'ABRAHAM', ' LEONARDO G.');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (3, 'ABRAHAM', ' VICTOR MIGUEL');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (4, 'ADROVER', ' RUBEN ATILIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (5, 'AGUDO', ' JORGE ALFONSO EXEQUIEL');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (6, 'AGUIRRE', ' ALBERTO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (7, 'AQUINO', ' RICARDO HORACIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (8, 'ARANDA', ' LEANDRO ARIEL');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (9, 'AVUT', ' ALEJANDRO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (10, 'BACIGALUPO', ' FEDERICO JOSE');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (11, 'BALLESTA', ' ALBERTO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (12, 'BERTIN', ' MARIA ALEJANDRA');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (13, 'BERTUZZI', ' MARCELO EMILIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (14, 'BIANCUCCI', ' IGNACIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (15, 'BORDOGNA', ' JOSE ALFREDO JAVIER');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (16, 'BUNIVA', ' JERONIMO OSCAR');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (17, 'BUNIVA', ' OSCAR LUIS');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (18, 'BUSTAMANTE', ' NICOLAS HERNAN');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (19, 'CALVET', ' RAMON SIXTO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (20, 'CALVO', ' JUAN MANUEL');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (21, 'CALVO', ' PABLO IGNACIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (22, 'CALVO', ' SANTIAGO JAVIER');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (23, 'CANDIDORI', ' ROMINA PAOLA');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (24, 'CARBALLADA', ' DANIEL EMILIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (25, 'CATALDO', ' MARIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (26, 'CELERI', ' PEDRO PABLO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (27, 'COLLI', ' ARTURO JUAN');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (28, 'COSTELA', ' GERARDO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (29, 'CRESPI', ' MARIA ELISABET');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (30, 'DALLA FONTANA', ' AGUSTIN');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (31, 'DALLO', ' IGNACIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (32, 'DAVID', ' MARIO MARCOS');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (33, 'DE AZCUENAGA', '  MARTIN NICOLAS');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (34, 'DE AZCUENAGA', ' MARTIN VIRGILIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (35, 'DE AZCUENAGA', ' MIGUEL');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (36, 'DE AZCUENAGA', ' MIGUEL A.');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (37, 'DE LIA', ' PABLO ARIEL');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (38, 'DOMINGORENA', ' STELLA MARIS');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (39, 'DOMINGUEZ MATHEU', ' MIGUEL ANGEL VICENTE');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (40, 'DRAGO', ' OSCAR ERNESTO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (41, 'EGEA', ' MARIANO A.');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (42, 'ESPOSITO', ' JULIO ALBERTO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (43, 'ESPOSITO', ' NICOLAS');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (44, 'ESQUIVEL', ' LUCIANO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (45, 'FALCO', ' ADRIAN ANTONIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (46, 'FIORETTI', ' DANIEL SEBASTIAN');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (47, 'FRETES', ' PABLO GERMAN');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (48, 'GAGGIOTTI', ' GABRIEL');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (49, 'GALLOTTO', ' LUCIANO MIGUEL');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (50, 'GAMBOZ', ' ALFREDO ROBERTO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (51, 'GAUTERO', ' LEANDRO MARTIN');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (52, 'GHIETO', ' FABIAN ANDRES');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (53, 'GONZALEZ', ' ANDRES FEDERICO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (54, 'GORLA', ' FEDERICO JOSE');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (55, 'GOROSTEGUI', ' PATRICIA ALEJANDRA');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (56, 'GOZALBES', ' VICENTE ALEXIS');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (57, 'GREMINGER', ' MARCELO LUIS');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (58, 'GRIN', ' SEBASTIAN');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (59, 'GUALA', ' AGUSTIN JOSE');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (60, 'GUNTERN', ' PABLO SEBASTIAN');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (61, 'ITO', ' OSCAR AKIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (62, 'JORGE', ' DIEGO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (63, 'JULLIER', ' RICARDO RODOLFO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (64, 'LAFUENTE', ' ANDRES');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (65, 'LANZA', ' RODRIGO G.');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (66, 'LUCCA', ' JAVIER');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (67, 'MENDOZA', ' LUCIANO FRANCISCO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (68, 'MEOLI', ' DANIEL CARLOS');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (69, 'MIGLIORINI', ' EUGENIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (70, 'MORALES', ' GUILLERMO LUIS');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (71, 'MOYA', ' CARLOS BERNARDO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (72, 'MURIEL', ' OMAR');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (73, 'MUZZACHIODI', ' EDUARDO IGNACIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (74, 'OLEINIZAK', ' EMANUEL ANDRES');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (75, 'PACHER', ' NICOLAS R.');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (76, 'RESTALDI', ' IGNACIO ARGENTINO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (77, 'REZETT', ' CARLOS N.');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (78, 'RIBERO', ' LUIS AUGUSTO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (79, 'SCHMIDT', ' ROMINA VIVIAN');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (80, 'SELDES', ' JUAN MAURICIO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (81, 'SERPENTIELLO', ' PABLO FERNANDO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (82, 'TREVISANI', ' RAUL RICARDO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (83, 'UNZUE', ' CRISTIAN');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (84, 'VALDES', ' MARIANO ARTURO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (85, 'VEGA', ' EDUARDO O.');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (86, 'WADE', ' ROLANDO ');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (87, 'WISNIEWISKI', ' PABLO');
INSERT INTO "profesional" ("id", "apellido", "nombre") VALUES (88, 'ZARCON', ' JOSE ALBERTO');
