spring:
  application:
    name: higea-turnos
server:
  port: 36003
  tomcat:
    max-threads: 4
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

feign:
  hystrix:
    enabled: false

