spring:
  resources:
    chain:
      enabled: true
  application:
    name: core-server
server:
  port: 36000
  tomcat:
    max-threads: 4
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

jwt:
  header: Authorization
  secret: my-very-secret-key

logging:
  level:
    org.springframework.security: DEBUG

management:
  security:
    enabled: true # set to false to disable 'default' Spring Boot security
