spring:
  resources:
    chain:
      enabled: true
  application:
    name: gateway
server:
  port: 8080
  tomcat:
    max-threads: 4
  ssl:
      key-store: classpath:keystore.p12
      key-store-password: turn3r0sslf0ld3r
      keyStoreType: PKCS12
      keyAlias: tomcat
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
        timeout:
          enabled: false
zuul:
  add-host-header: true
  routes:
    higea-profesionales:
      path: /higea/profesional/**
      url: http://localhost:36001
    higea-especialidades:
      path: /higea/especialidad/**
      url: http://localhost:36002
    higea-turnos-microservice:
      path: /higea/turnos/**
      url: http://localhost:36003
    higea-metadata-microservice:
      path: /higea/**
      url: http://localhost:36004
    core-server:
      path: /core/**
      sensitiveHeaders:
      url: http://localhost:36000