spring:
  application:
    name: higea-feign-client
server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}

#feign:
#  hystrix:
 #   enabled: false

hystrix:
  command:
    default:
      execution.isolation.thread.timeoutInMilliseconds: 8000
      fallback.enabled: false

